server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: "jdbc:mysql://localhost:3306/bookstore?serverTimezone=UTC"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "123456"
  web:
    resources:
      static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath*:mybatismapper/*.xml
  config-location: classpath:/mybatis-config.xml
